/*
 * This source file was generated by the Gradle 'init' task
 */
package bankproject;

public class App {
    public static void main( String[] args ) {
      //Database.createDatabase(); //Only used for testing purposes, if you want to reset the database for any reason uncomment this
      Menu menu = new Menu();
      menu.printMainMenu();
   }
}
